### ISSUE TITLE
hi, did you try in on Centos7?

### ISSUE THREAD

**Issue by zhuyw05** [dmikushin/binance-cxx-api#1]
git clone https://github.com/dmikushin/binance-cxx-api.git
cd binance-cxx-api
mkdir build
cd build/
cmake ..
./example

After cmake ..
I did not find an example under build directory. 

./example
won't run.

Did you miss any command? Thanks.

Best.

                               Alex

**Comment by HudsonHughes** [comment]
I am also dealing with this under Ubuntu.

**Comment by dmikushin** [comment]
Thanks for spotting this, it's just a `make` command is missing in the README, I've added it in commit 41df1e0827019efca963d9fe17dd0638002d4eb4
