### ISSUE TITLE
mbedcrypto error not built by this project

### ISSUE THREAD

**Issue by HugoKooijman** [dmikushin/binance-cxx-api#11]
Hello,

When following the installation instructions of this library, executing the cmd "cmake .." in the build directory causes the following error:

CMake Error at CMakeLists.txt:31 (target_link_libraries):
  Cannot specify link libraries for target "mbedcrypto::mbedcrypto" which is
  not built by this project.

Do I need to install mbedcrypto separately, and if so wich one? Because there are multiple mbedcrypto git repos.
(Thank you for your time)

**Comment by dmikushin** [comment]
Hi, which OS is that?

**Comment by HugoKooijman** [comment]
lsb_release -a result:

No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.2 LTS
Release:	18.04
Codename:	bionic

**Comment by amir963** [comment]
I had the same problem with ubuntu 18.04.4. you should upgrade cmake to solve the problem

**Comment by dmikushin** [comment]
I've just tested the following:

```
dmikushin@hyperthon:~/binance-cxx-api/build$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.4 LTS
Release:	18.04
Codename:	bionic
```

Top commit is 469d60ba678074f663415f3f3b9c07051943c86a CMake version is 3.16.5 

CMake configure is successful.

**Comment by dmikushin** [comment]
Thanks @amir963 Indeed, CMake version can really make the difference. @HugoKooijman you can get the latest CMake for Ubuntu from their official repository: https://apt.kitware.com/

I will try to figure out the actual minimum CMake version requirement and will add it to the project.

**Comment by dmikushin** [comment]
According to releases atop of https://gitlab.kitware.com/cmake/cmake/-/commit/8ffc1c3d89a5562d40a5bd86c457a3173a1469d0 , the proper version requirement is CMake 3.10. I've enforced this requirement for us in bc5a37bb72c3e653d7272613fba3b8331f911aaf

**Comment by HugoKooijman** [comment]
I updated my CMake and that did indeed fix this particular error, thank you.

**Comment by amir963** [comment]
@dmikushin the default cmake version of ubuntu 18.04 is 3.10.2
https://packages.ubuntu.com/search?keywords=cmake&searchon=names&suite=bionic&section=all
so 3.10 for the minimum version is not enough on the other hand the cod can be compiled on ubuntu 19.10 with cmake version 3.13.4 without any problem. hence the correct version is somthing between 3.10.2 and 3.13.4

**Comment by dmikushin** [comment]
@amir963 Corrected as you adviced, thanks!
