### ISSUE TITLE
Certificate error?

### ISSUE THREAD

**Issue by woutervanh** [dmikushin/binance-cxx-api#3]
I get following error while trying to run the example:

[2019/04/01 20:23:07:5422] NOTICE: lws_protocol_init
[2019/04/01 20:23:07:8858] ERR: SSL connect error 337047686: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed
2019-04-01 20:23:07 885877 :<binance::Websocket::event_cb> LWS_CALLBACK_CLIENT_CONNECTION_ERROR

Any idea?

**Comment by paranoja888** [comment]
Hello Wouter,
I have the same issue.
Do you have any solution? If you fixed this problem could you please share information. Thanks in advance.

**Comment by HudsonHughes** [comment]
Did anyone ever solve this

**Comment by dmikushin** [comment]
The easiest is you should try Ubuntu 16.04 instead of 18.04, where SSL
libraries versions are different, which introduces this problem.

сб, 18 мая 2019 г. в 07:04, Hudson Hughes <notifications@github.com>:

**Comment by dmikushin** [comment]
@woutervanh @paranoja888 @HudsonHughes Dear all, please try 108d2edef6bfd1f61bbec33a998d78be821f04d0 The idea is that the project now incorporates the proper LWS as a source code and compiles it in, regardless of what LWS is available within the host system. For me this unbreaks Ubuntu 18.04, could you please check?
