### ISSUE TITLE
ubuntu  Segmentation fault

### ISSUE THREAD

**Issue by mussonero** [dmikushin/binance-cxx-api#8]
I am getting  Segmentation Fault, just by executing  "account.getInfo(json_result, recvWindow)"

Program received signal SIGSEGV, Segmentation fault.
0x00007fbf4151abd6 in mbedtls_sha256_finish_ret (ctx=0x55658cd7faf0, output=0x2af8 <error: Cannot access memory at address 0x2af8>) at /opt/binance-cxx-api/ThirdParty/mbedtls/crypto/library/sha256.c:386
386	    PUT_UINT32_BE( ctx->state[0], output,  0 );

**Comment by dmikushin** [comment]
Dear @mussonero please bump to db3bc5046c2a17d890e639b5cb181b86b03a3120 where I've fixed a very silly typo I've made recently.

**Comment by mussonero** [comment]
Yep it works,
Thank you 👍
